name: Build and Push to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker us.gcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-app:$GITHUB_SHA

      - name: Post Image URI
        run: |
          echo "Image URI: gcr.io/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-app:$GITHUB_SHA"
