name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'docker'

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev -q

      - name: Build the Docker Image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-gcr/tdw-kt-img:$GITHUB_SHA .

      - name: Push the Docker Image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-gcr/tdw-kt-img:$GITHUB_SHA

      - name: Post Image URI
        run: |
          echo "Image URI: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-gcr/tdw-kt-img:$GITHUB_SHA"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tdw-kt-service \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tdw-kt-gcr/tdw-kt-img:$GITHUB_SHA \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Post Deployment URL
        run: |
          SERVICE_URL=$(gcloud run services describe tdw-kt-service --region=us-central1 --format='value(status.url)')
          echo "Cloud Run Service URL: $SERVICE_URL"
